### ISSUE TITLE
ceph pool data hernoemen

### ISSUE THREAD

**Issue by AtzeDeVries** [naturalis/storage-analytics#1]
De `data` pool wordt in ceph niet gebruikt. Ik ga er van uit dat de `data` pool zou moeten verwijzen naar object store.

In principe staat de data dan in `.rgw.buckets` met een aantal andre pools die wat metadata beheren. Het lijkt me beter dat `data` `buckets` wordt. Ik denk dat het dan duidelijker is

**Comment by davidheijkamp** [comment]
We gebruiken nu `buckets` in het voorbeeld.
